# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 05:17
from __future__ import unicode_literals

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('file_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('policy', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
            },
        ),
    ]
